# Generated by Django 5.2.1 on 2025-06-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('Rendah', 'Rendah'), ('Sedang', 'Sedang'), ('Tinggi', 'Tinggi')], default='sedang', max_length=10),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Tertunda', 'Tertunda'), ('Selesai', 'Selesai')], default='tertunda', max_length=10),
        ),
    ]
