# Generated by Django 5.2.1 on 2025-06-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_priority_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('low', 'Rendah'), ('medium', 'Sedang'), ('high', 'Tinggi')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('pending', 'Tertunda'), ('completed', 'Selesai')], default='medium', max_length=10),
        ),
    ]
