# Generated by Django 5.2.1 on 2025-06-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_priority_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('study', 'Study'), ('shopping', 'Shopping'), ('health', 'Health'), ('hobby', 'Hobby')], default='personal', max_length=20),
        ),
    ]
